name: 302-bot

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - TOKEN=${TOKEN}
    depends_on:
      - redis
      # - postgres

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-postgres}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB:-postgres}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  # postgres_data:
