name: Run checks

on:
  pull_request:
    types: [ready_for_review]
    branches:
      - main
      - master
      - dev

jobs:
    lint:
        name: Lint
        runs-on: blacksmith-4vcpu-ubuntu-2404
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: useblacksmith/setup-node@v5
              with:
                  node-version: 20
              
            - name: Install dependencies
              run: npm i

            - name: Run server
              run: npm run lint
              
    typecheck:
        name: Typecheck
        runs-on: blacksmith-4vcpu-ubuntu-2404
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: useblacksmith/setup-node@v5
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm i

            - name: Run client
              run: npm run typecheck